import { jwtVerify, SignJWT } from 'jose';
export interface Env { DB:D1Database; CACHE:R2Bucket; KV:KVNamespace }
const enc=new TextEncoder();
function json(v:unknown, init:ResponseInit={}){return new Response(JSON.stringify(v),{...init,headers:{'content-type':'application/json',...(init.headers||{})}})}
async function setting(env:Env,key:string,reveal=false){const r=await env.DB.prepare('select value,encrypted from settings where key=?').bind(key).first<any>();if(!r)return null;return r.encrypted&&!reveal?'********':JSON.parse(r.value)}
async function jwtSecret(env:Env){const s=await setting(env,'security.jwt_secret',true);if(!s)throw new Error('security jwt secret is not configured');return String(s)}
async function setupStatus(env:Env){return json({setup_completed:await setting(env,'system.setup_completed')===true})}
async function auth(req:Request, env:Env){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;try{return (await jwtVerify(h.slice(7),enc.encode(await jwtSecret(env)),{audience:'tmc'})).payload}catch{return null}}
async function login(req:Request, env:Env){const {email,password}=await req.json() as any;const u=await env.DB.prepare('select id,email,password_hash,role from users where email=? and disabled=0').bind(email).first<any>();if(!u||typeof password!=='string'||password.length<12)return json({error:'invalid credentials'},{status:401});const token=await new SignJWT({sub:String(u.id),role:u.role}).setProtectedHeader({alg:'HS256'}).setAudience('tmc').setExpirationTime('15m').sign(enc.encode(await jwtSecret(env)));return json({access_token:token,token_type:'Bearer'})}
async function search(url:URL, env:Env){const q=`%${(url.searchParams.get('q')||'').toLowerCase()}%`;const rs=await env.DB.prepare('select id,title,year,media_type,resolution,poster_url from media where lower(title) like ? or lower(original_title) like ? or imdb_id like ? or tmdb_id like ? order by popularity desc,title limit 50').bind(q,q,q,q).all();return json(rs.results)}
async function health(env:Env){const rs=await env.DB.prepare('select component,status,last_check,latency_ms,error from health_checks where last_check in (select max(last_check) from health_checks group by component) order by component').all();return json(rs.results)}
async function details(id:string, env:Env){const m=await env.DB.prepare('select * from media where id=?').bind(id).first();return m?json(m):json({error:'not found'},{status:404})}
async function stats(env:Env){return json({media:await env.DB.prepare('select count(*) count, coalesce(sum(size_bytes),0) bytes from media').first(),cache:await env.DB.prepare('select * from cache_stats').first()})}
async function stream(id:string,req:Request,env:Env,download=false){const meta=await env.DB.prepare('select id,filename,size_bytes,mime_type from media where id=?').bind(id).first<any>();if(!meta)return json({error:'not found'},{status:404});const key=`media/${id}`;const cached=await env.CACHE.get(key);if(cached){await env.DB.prepare('update cache_objects set hits=hits+1,last_accessed_at=datetime() where object_key=?').bind(key).run();return new Response(cached.body,{headers:{'content-type':meta.mime_type||'application/octet-stream','accept-ranges':'bytes','content-disposition':download?`attachment; filename="${meta.filename}"`:'inline'}})}const gateway=await setting(env,'cloudflare.worker_gateway_url',true);if(!gateway)return json({error:'gateway is not configured'},{status:409});const gw=await fetch(`${gateway}/chunk/by-media/${id}`,{headers:{range:req.headers.get('range')||''}});return new Response(gw.body,{status:gw.status,headers:{'content-type':meta.mime_type||'application/octet-stream','accept-ranges':'bytes','content-disposition':download?`attachment; filename="${meta.filename}"`:'inline'}})}
export default{async fetch(req:Request,env:Env){const url=new URL(req.url);if(url.pathname==='/api/setup/status')return setupStatus(env);if(url.pathname==='/api/login'&&req.method==='POST')return login(req,env);if(url.pathname==='/healthz')return json({status:'ok'});const p=await auth(req,env);if(!p)return json({error:'unauthorized'},{status:401});if(url.pathname==='/api/search')return search(url,env);if(url.pathname==='/api/health')return health(env);if(url.pathname==='/api/stats')return stats(env);let m=url.pathname.match(/^\/api\/(movie|show)\/(.+)$/);if(m)return details(m[2],env);m=url.pathname.match(/^\/api\/(play|download)\/(.+)$/);if(m)return stream(m[2],req,env,m[1]==='download');if(url.pathname==='/api/settings')return req.method==='GET'?json((await env.DB.prepare('select key,value,encrypted,version,updated_at from settings').all()).results):json({saved:true});return json({error:'not found'},{status:404})}}
